### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
We are working with dr.lt.data and comfyanon to build a global registry for custom nodes (similar to PyPI). Eventually, the registry will be used as a backend for the UI-manager. All nodes go through a verification process before being published to users.

The main benefits are that authors can
- publish nodes by version and users can safely update nodes knowing ahead of time if their workflows will break or not
- automate testing against new commits in the comfy repo and existing workflows through our CI/CD dashboard

Action Required:

- [ ] Go to the [registry](https://registry.comfy.org). Login and create a publisher id. Add the publisher id into the pyproject.toml file.
- [ ] Write a short description.
- [ ] Merge the separate Github Actions PR and run the workflow.

If you want to publish the node manually, [install the cli](https://docs.comfy.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`

Check out our [docs](https://docs.comfy.org/registry/overview#introduction) if you want to know more about the registry. Otherwise, feel free to message me on discord at haohao_81202 or join our [server](https://discord.com/invite/comfyorg) if you have any questions!

### CODE REVIEW

**Comment by haohaocreates** [comment]
hey @vsevolod-oparin, wanted to send a small nudge and ask if you had any questions!

**Comment by vsevolod-oparin** [comment]
Hey @haohaocreates , I was AFK for few months. Sure, I’ll check it out and will let you know if I have any. But it will be approximately in two weeks from now.

**Comment by haohaocreates** [comment]
Sweet! Lmk if you have any other questions then hehe

**Comment by vsevolod-oparin** [comment]
Yeah, just checked from the phone what I can do now. What do you mean by description in the second check box? Is it here? Or in registry?

Also, thank you for organizing all plugins on one registry!

**Comment by haohaocreates** [comment]
hey @vsevolod-oparin ! haha don't sweat it! so after you create a publisher id you just have to fill in the publisherID field in the pyproject.toml file! 

in this case, the description seems to already be filled in in the pyproject.toml so after you add the publisherID you should be good to follow the rest of the instructions!

this is a link to the docs btw!: http://docs.comfy.org/registry/overview#introduction

**Comment by vsevolod-oparin** [comment]
Added toml config and icon by commit 3480c082ac5d1cf09ae05ef919be6d7902a43056

**Comment by vsevolod-oparin** [comment]
Closing

**Comment by vsevolod-oparin** [comment]
@haohaocreates Let me know if you need anything more from my side. Thanks again for organizing the plugins

**Pull request closed without merging**
